### ISSUE TITLE
Support for Custom Spans

### ISSUE THREAD

**Issue by ahtik** [instana/nodejs-sensor#107]
I'm excited to read about PHP support for more granular tracing at https://www.instana.com/blog/illuminate-critical-php-code-with-custom-spans/ and tried to find out how to set it up for the nodejs sensor.

Is this kind of use possible with an Instana NodeJS sensor? I did try to look up from the code and docs but failed to find a reference.

**Comment by basti1302** [comment]
Hi ahtik,

currently this is not supported in Node.js. We have support for OpenTracing (https://github.com/instana/nodejs-sensor#opentracing) but OpenTracing spans can never be combined with spans created by out automatic tracing capabilities, so our OpenTracing support will not give you the same functionality as described in the PHP blog post.

If you would like to see that functionality added to the Node.js sensor, would please create a feature  request at https://support.instana.com/hc/en-us/requests/new for it? Alternatively, if you are using npm packages that we currently do not instrument, you could also add feature requests for auto-instrumentation for them.

Kind regards

  Bastian

**Comment by amirilovic-adidas** [comment]
Hi, I see this issue is very old, are there any updates on combining automatic tracing and custom spans in nodejs? 
I see docs still suggest that with open tracking automatic tracing should be disabled https://docs.instana.io/ecosystem/node-js/api/#opentracing-integration

Also one suggestion for docs, would be good to explain why to disable automatic tracing and what is result in one or the other case, currently it just says "should" but no explanation what is the outcome if not disabled.
Thanks!

**Comment by RecuencoJones** [comment]
@amirilovic-adidas looks like that's possible! I have created some example and it's even possible to link custom spans to automatic spans

Information about usage can be found here: https://www.instana.com/blog/instana-announces-support-opentracing/

I think documentation should reflect this use case as it can be really useful!

**Comment by basti1302** [comment]
This issue is indeed very old. In the meantime, we have added an SDK to create custom spans: https://docs.instana.io/ecosystem/node-js/api/#creating-spans-manually-with-the-sdk

Custom spans created via the SDK integrate seamlessly with auto-tracing spans. On the other hand, combining auto-tracing spans with OpenTracing is not officially supported.

Thus, if you want to enhance Instana's Node.js auto tracing with custom spans, the SDK is the way to go.

This is also reflected in the documentation you linked to (see the section "Limits"):

> OpenTracing is not integrated with Instana’s automatic tracing. In particular, spans created by using the OpenTracing API will not be part of the same trace as the spans created by our automatic tracing instrumentation. If you want to add additional spans to the automatically created spans, you should prefer the SDK over OpenTracing. In fact, we recommend to either use automatic tracing (optionally augmented by SDK spans) or OpenTracing, but not both in one application.

**Comment by amirilovic-adidas** [comment]
@RecuencoJones @basti1302  Thanks for the info, will try to add to my app. Cheers!
