### ISSUE TITLE
Windows: `Pre-built version of AutoProfile is not available (ABI not found), fallback to node-gyp. node-gyp not found.`

### ISSUE THREAD

**Issue by oszbart** [instana/nodejs-sensor#241]
Hello,

I added dependency to `@instana/autoprofile` package inside my app. On Unix/Mac everything seems fine. However on Windows while doing npm install I get following error:
```shell
Pre-built version of AutoProfile is not available (ABI not found), fallback to node-gyp.
node-gyp not found.
``` 

This prevents people developing on Windows to setup app locally. I checked couple of times that node-gyp works fine on my machine, I am able to build some popular packages using node-gyp (for example: node-sass, bcrypt).

I am not an expert, but I figured out that spawning process inside https://github.com/instana/nodejs-sensor/blob/master/packages/autoprofile/node-gyp-fallback.js#L20 does not work as expected. I figured out two potential fixes:

```javascript
var command = os.platform() === 'win32' ? 'node-gyp.cmd' : 'node-gyp';
var gyp = child_process.spawn(command, ['rebuild'], { cwd: process.cwd(), env: process.env, stdio: 'inherit' });
```

OR

```javascript
var gyp = child_process.spawn('node-gyp', ['rebuild'], { cwd: process.cwd(), env: process.env, stdio: 'inherit', shell: true });
```

If I need to provide some more info, please let me know, I would be happy to help.

**Comment by basti1302** [comment]
Thanks for the report, I'll take a look soon.

**Comment by basti1302** [comment]
Just to clarify, this should not be an issue for using the Instana Node.js collector at all, even on Windows. 

First of all:
> I added dependency to @instana/autoprofile package inside my app. 

You actually should not do that, at all. Applications should depend on `@instana/collector` and not directly on `@instana/autoprofile`. Why would you want to depend on the autoprofile package directly?

The package `@instana/collector` in turn declares an optional dependency on `@instana/autoprofile`. When installing the dependencies for your application on Windows, you will see some messages about npm/yarn not being able to install `@instana/autoprofile`, because this is currently not supported on Windows (which we will fix eventually). But since this is an optional dependency, the installation will still succeed anyway.

**Comment by oszbart** [comment]
Thanks for hint, I will check why it was added this way and will get back to you if this would fix our issue.

**Comment by oszbart** [comment]
@basti1302 I confirm that after removing @instana/autoprofile from package.json everything works fine, thanks for support.
