### ISSUE TITLE
enable the sensor transparent to the app

### ISSUE THREAD

**Issue by gireeshpunathil** [instana/nodejs-sensor#297]
As per the doc, currently the Node.js sensor is enabled by modifying the application thus:

```js
require('@instana/collector')();
```

Node.js provides at least two ways to source the module into the app without modifying the source:

 - `export NODE_OPTIONS='--require "@instana/collector"'` on the invoking shell
https://nodejs.org/dist/latest-v15.x/docs/api/cli.html#cli_node_options_options
 - `node -r @instana/collector <app>`
https://nodejs.org/dist/latest-v15.x/docs/api/cli.html#cli_r_require_module

both preload the module into the app, after the core module bootstrap, but before any app module is loaded.

The only caveat is that the `()` part of `require('@instana/collector')()` needs to be refactored - which function is being invoked here, needs to be executed outside of that function, at the time of sourcing the module itself.

Hope this make sense?

**Comment by basti1302** [comment]
Hi,

we have this covered already. See here: 

https://www.instana.com/docs/ecosystem/node-js/installation#installation-without-modifying-the-source-code

We unfortunately cannot change our main export due to backwards compatibility, thus `NODE_OPTIONS='--require "@instana/collector"'` will not work but `NODE_OPTIONS="--require ./node_modules/@instana/collector/src/immediate"` will do what you are looking for as per the documentation I linked to above.

Does that help?

**Comment by gireeshpunathil** [comment]
@basti1302 - ah, missed that earlier, thanks for the clarification. Yes, that helps!
