### ISSUE TITLE
Update to `node-gyp@8.0.0`

### ISSUE THREAD

**Issue by rtrys** [instana/nodejs-sensor#325]
hi, [node-gyp@8.0.0](https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md#v800-2021-04-03) is released and here is replacing deprecated [request](https://github.com/request/request), would be nice to have an update for this module in instana packages, I hope you can consider this update

**Comment by basti1302** [comment]
As I said in #313 

> About node-gyp@8, I didn't look into it but since the release notes say they dropped support for Python 2 I am pretty sure we cannot move to that version soon. We need to support a lot of customers with a wide range of setups and I'm pretty sure there are still quite a few scenarios where @instana/collector is installed when Python 2 is the default Python.

We update dependencies periodically after evaluating if the upgrade is feasible, keeping in mind all usage scenarios of `@instana/collector`. The same will happen with node-gyp, that is, we will move to version 8 eventually. 

I don't think it is particularly helpful to keeping an issue for one particular dependency open, potentially for a longer time so I am going ahead and close this one. But thanks for bringing it up.

I the node-gyp version we are using poses an actual problem for your use case, you are welcome to create an issue at https://support.instana.com/hc/en-us/requests/new.

**Comment by rtrys** [comment]
Hi @basti1302, thanks for your comments, I hope you can help me to have a better understanding, 

```bash
──┬ @instana/collector@1.119.1
  └─┬ @instana/autoprofile@1.119.1
    └─┬ node-gyp@7.1.2
      └── request@2.88.2 
```

the reason I requested an updated, is because request@2.88.2 has a few [security issues](https://sca.analysiscenter.veracode.com/vulnerability-database/libraries/request/JS/NPM/lid-675/versions/2.88.2), and since it will require more than a simple update to have latest version, I would like to have a better idea how it could affect us, I have the idea that `node-gyp` is used only for compile matters, but I appreciated if you can give me a few more details or correct me if I am wrong

**Comment by basti1302** [comment]
Hey, sure.

node-gyp is used to compile native add-ons (npm modules that contain C++ code in addition to pure Javascript). As such, it will _only_ become active during `npm install`, not while you actually run your application. It depends on request because it tries to download precompiled binaries for the target operating system instead of actually compiling the C++ code during `npm install`,  if possible (because downloading is faster than compiling). So the security issues are not relevant, as the request code will not be used while the application is running.

If you are really bothered by this, you can also run `npm install --no-optional`, which will omit all optional dependencies from being installed (`@instana/autoprofile` is an optional dependency). But without optional dependencies you will also lose some metrics (gc metrics, some event loop metrics).

**Comment by rtrys** [comment]
thanks, I really appreciated your quick answer

**Comment by RobertTheBlair** [comment]
Thanks Bastian. I believe we will be able to mitigate tool-chain risks here by ensuring our build systems only pull from authorized locations.
Toolchain attacks have been increasing in cleverness, and we want to be very certain about what bits we ship.
