### ISSUE TITLE
HTTPS client tracing

### ISSUE THREAD

**Issue by schmod** [instana/nodejs-sensor#33]
Is there support for tracing outgoing HTTPS requests on the roadmap?

**Comment by bripkens** [comment]
Are you referring to execution of HTTP requests via the `https` module? So that would be `require('https').request(…)`? I think this was just an oversight possibly based on the assumption that `https.request` just delegates to `http.request` (which it doesn't in Node.js/master).

Implementation for this will most likely be simple, but I don't have time to take care of the tests right now. I can try to take a look at it late next week.

**Comment by schmod** [comment]
Yep.  Thanks for offering to take a look!

**Comment by pglombardo** [comment]
This was added and released in 1.30.2: https://github.com/instana/nodejs-sensor/blob/master/CHANGELOG.md#1302

**Comment by schmod** [comment]
The change in 1.30.2 was for HTTP servers; not clients.

**Comment by pglombardo** [comment]
Doh you're right.  Thanks for pointing out.  I glanced too quickly at this.
